### NUMPY REVISION 

Awesome Cheatsheet at : https://www.dataquest.io/blog/numpy-cheat-sheet/

#### Creating a Numpy Array

Ranks in Numpy Arrays: number of dimensions of the array is called rank of the array. 

In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [5]:
len(a)

3

In [7]:
#array with rank 2
a = np.array([[1,2,3],[2,3,4]])                      #note : ([[...],[...]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [9]:
len(a)   #a.size

3

In [13]:
a.shape

(3,)

In [8]:
#Array using tuple
a = np.array((1,2,3))
a

array([1, 2, 3])

#### Accessing the array Index : Basic Indexing

In [15]:
b = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])
b

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [16]:
b[0:2]

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ]])

In [17]:
b[:,0:2]

array([[-1. ,  2. ],
       [ 4. , -0.5],
       [ 2.6,  0. ],
       [ 3. , -7. ]])

#### Array with first 2 rows and columns:

In [18]:
b[:2,:2]

array([[-1. ,  2. ],
       [ 4. , -0.5]])

##### Array with first 2 rows and alternate columns(0 and 2):

In [59]:
#start:stop:step
b = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

print(b[:2,0:4:2])  #give start stop step in column

#print(b[:3,0:4,2])    : error : 2d array

sliced_arr = b[:2, ::2]
print ("Array with first 2 rows and"
    " alternate columns(0 and 2):\n", sliced_arr)

[[-1.  0.]
 [ 4.  6.]]
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]


In [28]:
# Create a sequence of integers from 10 to 1 with a step of -2
c = np.arange(10, 1, -2)
print("c is",c)

# Indexes are specified inside the np.array method.
newarr = c[np.array([3, 1, 2 ])]
print("\n Elements at these indices in c are:\n",newarr)

c is [10  8  6  4  2]

 Elements at these indices in c are:
 [4 8 6]


#### Basic Slicing:

In [33]:

d = np.arange(20)
print("\n Array d is:\n ",d)
  
# d[start:stop:step]
print(d[-4:19:2]) 
  
# The : operator means all elements till the end.
print(d[10:])


 Array d is:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[16 18]
[10 11 12 13 14 15 16 17 18 19]


#### Ellipsis:

Ellipsis can also be used along with basic slicing. Ellipsis (…) is the number of : objects needed to make a selection

In [55]:
#A 3 dimensional array.
b = np.array([[[1, 2, 3],[4, 5, 6]],
              [[7, 8, 9],[10, 11, 12]]])
print("b is",b)

print("\nb[:1] is",b[:1])

print("\nb[1:2] is",b[1:2])

#Start,stop,step:

print("\nb[: ,: ,1 ] is:", b[: ,: ,1 ])  #thus prints middle element

b is [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

b[:1] is [[[1 2 3]
  [4 5 6]]]

b[1:2] is [[[ 7  8  9]
  [10 11 12]]]

b[: ,: ,1 ] is: [[ 2  5]
 [ 8 11]]


In [162]:
b = np.array([[[1, 2, 3],[4, 5, 6]],
              [[7, 8, 9],[10, 11, 12]]])
 
print(b[...,1]) #Equivalent to b[: ,: ,1 ]

[[ 2  5]
 [ 8 11]]


#### Boolean Indexing
This indexing has some boolean expression as the index. Those elements are returned which satisfy that Boolean expression. It is used for filtering the desired element values.

In [60]:
a = np.array([10, 40, 80, 50, 100])
print(a[a>50])

[ 80 100]


In [61]:
a = np.array([10, 40, 80, 50, 100])
print(a[a%40==0]**2)

[1600 6400]


Axis 0 will act on all the ROWS in each COLUMN
Axis 1 will act on all the COLUMNS in each ROW
Basically simplest to remember it as 0=down and 1=across.

In [77]:
b = np.array([[5, 5,0],[4, 5,1],[16, 4,5]])
print(b)

sumrow = b.sum(1)
print("\n",b[sumrow%10==0])

sumcolumn = b.sum(0)
print("\n",b[:,sumcolumn%2==0])

[[ 5  5  0]
 [ 4  5  1]
 [16  4  5]]

 [[5 5 0]
 [4 5 1]]

 [[5 0]
 [5 1]
 [4 5]]


In [85]:
# basic operations on single array

# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])
               
# Adding 1 to every element
print ("Adding 1 to every element:", a + 1)
 
# Subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)
 
# sum of array elements
# Performing Unary operations
print ("\nSum of all array "
       "elements: ", a.sum())
 
# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)

print ("\nMean of all array "
       "elements: ", a.mean())

Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]

Mean of all array elements:  2.5


#### Unary operators: 

Many unary operations are provided as a method of ndarray class. This includes sum, min, max, etc. These functions can also be applied row-wise or column-wise by setting an axis parameter.

Axis 0 will act on all the ROWS in each COLUMN
Axis 1 will act on all the COLUMNS in each ROW

Basically simplest to remember it as 0=down and 1=across.

In [136]:
arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])
 
# maximum element of array
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",arr.max(axis = 1))
 
# minimum element of array
print ("Column-wise minimum elements:",
                        arr.min(axis = 0))
 
# sum of array elements
print ("Sum of all array elements:",
                            arr.sum())
 
# cumulative sum along each row
print ("Cumulative sum along each row:\n",
                        arr.cumsum(axis = 1))

# cumulative sum along each column
print ("Cumulative sum along each column:\n",
                        arr.cumsum(axis = 0))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]
Cumulative sum along each column:
 [[ 1  5  6]
 [ 5 12  8]
 [ 8 13 17]]


#### Universal functions (ufunc):

In [139]:
# create an array of sine values
a = np.array([1, np.pi/2, np.pi])
print("a is:",a)
print ("Sine values of array elements:", np.sin(a))
 
# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))
 
# square root of array values
print ("Square root of array elements:", np.sqrt(a))

a is: [1.         1.57079633 3.14159265]
Sine values of array elements: [8.41470985e-01 1.00000000e+00 1.22464680e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


### Data types in array

In [89]:
a.dtype

dtype('int32')

#### Math Operations on DataType array

In [93]:

arr1 = np.array([[4, 7],[2, 6]], dtype = np.float64)
                  
arr2 = np.array([[3, 6],[2, 8]], dtype = np.float64) 
 
#Addition of two Arrays
Sum = np.add(arr1, arr2)
print("Addition of Two Arrays: ",Sum)


# Addition of all Array elements
Sum1 = np.sum(arr1)
print("\nAddition of Array elements: ",Sum1)

 
# Square root of Array
Sqrt = np.sqrt(arr1)
print("\nSquare root of Array1 elements: ",Sqrt)
 
# Transpose of Array 
Trans_arr = arr1.T
print("\nTranspose of Array: ",Trans_arr)


Addition of Two Arrays:  [[ 7. 13.]
 [ 4. 14.]]

Addition of Array elements:  19.0

Square root of Array1 elements:  [[2.         2.64575131]
 [1.41421356 2.44948974]]

Transpose of Array:  [[4. 2.]
 [7. 6.]]


#### Dimesionality and Size of Array:

In [95]:
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5.0]] )
 
# Printing type of arr object
print("Array is of type: ", type(arr))
 
# Printing array dimensions (axes)              #Dimensions or Rank or Axes
print("No. of dimensions: ", arr.ndim)
 
# Printing shape of array
print("Shape of array: ", arr.shape)
 
# Printing size (total number of elements) of array
print("Size of array: ", arr.size)                            
 
# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  float64


In [155]:
z = np.zeros(5)
print("zeros",z)

z = np.ones((5,2))
print("ones",z)

z = np.full(5,2)
print("full",z)

z = np.full([5,4],3)
print("empty",z)

z = np.eye(5,4)
print("eye",z)

z= z.reshape([2,10])    #condition size of array must remain same , here 5*3=15
print("reshaped z:",z)

z = np.arange(10)        #returns evenly spaced values within a given interval. step size is specified.
print("arange",z)

z = np.arange(10,20,step=2)        #returns evenly spaced values within a given interval. step size is specified.
print("arange with step",z)

#linspace: returns evenly spaced values within a given interval. num no. of elements are returned.
z = np.linspace(10,19,num=10)           #last element is included
print("linspace is equal space by default",z)

zeros [0. 0. 0. 0. 0.]
ones [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
full [2 2 2 2 2]
empty [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
eye [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
reshaped z: [[1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
arange [0 1 2 3 4 5 6 7 8 9]
arange with step [10 12 14 16 18]
linspace is equal space by default [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]


In [134]:
z = np.full([5,4],3,dtype=complex)
print("empty",z)

empty [[3.+0.j 3.+0.j 3.+0.j 3.+0.j]
 [3.+0.j 3.+0.j 3.+0.j 3.+0.j]
 [3.+0.j 3.+0.j 3.+0.j 3.+0.j]
 [3.+0.j 3.+0.j 3.+0.j 3.+0.j]
 [3.+0.j 3.+0.j 3.+0.j 3.+0.j]]


#### Iterations:

In [146]:
a = np.full((3,2),2)
print(a)
for i in a:
    print(i)
    
b = np.full(3,6)
print("b is",b)

for i in b:
    print(i)

[[2 2]
 [2 2]
 [2 2]]
[2 2]
[2 2]
[2 2]
b is [6 6 6]
6
6
6


#### Flatten array: 
We can use flatten method to get a copy of array collapsed into one dimension. It accepts order argument. 

In [151]:
array = np.array([[1, 2], [3, 4]])
print("array is",array)
a = array.flatten()
print("a is:",a)

array is [[1 2]
 [3 4]]
a is: [1 2 3 4]


In [161]:
a = np.array([[0, 1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10, 11],
              [12, 13, 14, 15, 16, 17],
              [18, 19, 20, 21, 22, 23],
              [24, 25, 26, 27, 28, 29],
              [30, 31, 32, 33, 34, 35]])
             
print("\n a[0, 3:5]  = ",a[0, 3:5])    #prints only 0th row
             
print("\n a[2:;2, ::2]  = ",a[2::2, ::2]) 


 a[0, 3:5]  =  [3 4]

 a[2:;2, ::2]  =  [[12 14 16]
 [24 26 28]]


#### Advance Integer Indexing

Purely integer indexing : When integers are used for indexing. Each element of first dimension is paired with the element of the second dimension. So the index of the elements in this case are (0,0),(1,0),(2,1) and the corresponding elements are selected.

In [163]:
# Python program showing advanced indexing
import numpy as np
 
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]])                        
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])       #print element at (0,1),(1,0),(2,1)

[1 3 6]


In [1]:
#Code harry video Argsort, Argmin, Argmax and Others:

import numpy as np

#Way to make an array
#Using ARANGE : works like range

a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [7]:
b = np.array([1,45,67,32,46,78,98,46,32,11,12,33,53,4,63,2,5,21])
b.shape

(18,)

In [5]:
#Using Reshape:
# b.reshape(3,6)

array([[ 1, 45, 67, 32, 46, 78],
       [98, 46, 32, 11, 12, 33],
       [53,  4, 63,  2,  5, 21]])

In [6]:
# b.reshape(6,3)

array([[ 1, 45, 67],
       [32, 46, 78],
       [98, 46, 32],
       [11, 12, 33],
       [53,  4, 63],
       [ 2,  5, 21]])

In [10]:
np.argsort(b)

array([ 0, 15, 13, 16,  9, 10, 17,  3,  8, 11,  1,  7,  4, 12, 14,  2,  5,
        6], dtype=int64)

<!-- Output of Argsort is that indices that would sort this array. Example: b[0] was 1(lowest) hence given 0 indices -->

In [13]:
# Output of Argsort is that indices that would sort out this array.
#Example: in this case b[0]=1 is the lowest and thus given indices 0

#### numpy.nditer : Iterating over array

NumPy package contains an iterator object numpy.nditer. 

It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface.

In [170]:
a = np.arange(12).reshape(4,3)
print("a is:",a)

for i in np.nditer(a):
    print(i)

a is: [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
0
1
2
3
4
5
6
7
8
9
10
11


#### Binary Operations : Bitwise Operators : BITWISE OR,AND,XOR etc

Binary operators acts on bits and performs bit by bit operation. Binary operation is simply a rule for combining two values to create a new value.

In Python, bitwise operators are used to perform bitwise calculations on integers. The integers are first converted into binary and then operations are performed on bit by bit, hence the name bitwise operators.

#### numpy.bitwise_and() :

In [174]:
 
in_arr1 = [2, 8, 125]
in_arr2 = [3, 3, 115]
  
print ("Input array1 : ", in_arr1) 
print ("Input array2 : ", in_arr2)
   
out_arr = np.bitwise_and(in_arr1, in_arr2) 
print ("Output array after bitwise_and: ", out_arr) 

Input array1 :  [2, 8, 125]
Input array2 :  [3, 3, 115]
Output array after bitwise_and:  [  2   0 113]


#### numpy.bitwise_or() 

In [175]:
in_arr1 = [2, 8, 125]
in_arr2 = [3, 3, 115]
  
print ("Input array1 : ", in_arr1) 
print ("Input array2 : ", in_arr2)
   
out = np.bitwise_or(in_arr1,in_arr2)
print("Bitwise OR output: ", out)

Input array1 :  [2, 8, 125]
Input array2 :  [3, 3, 115]
Bitwise OR output:  [  3  11 127]


#### numpy.bitwise_xor() : 

In [176]:
in_arr1 = [2, 8, 125]
in_arr2 = [3, 3, 115]
  
print ("Input array1 : ", in_arr1) 
print ("Input array2 : ", in_arr2)
   
out = np.bitwise_xor(in_arr1,in_arr2)
print("Bitwise XOR output: ", out)

Input array1 :  [2, 8, 125]
Input array2 :  [3, 3, 115]
Bitwise XOR output:  [ 1 11 14]


#### numpy.invert() : bitwise NOT

This function is used to Compute the bit-wise Inversion of an array element-wise. It computes the bit-wise NOT of the underlying binary representation of the integers in the input arrays.

In [179]:
in_arr1 = [2, 8, 125]

print ("Input array1 : ", in_arr1) 

out = np.invert(in_arr1)
print("Bitwise NOT output: ", out)

Input array1 :  [2, 8, 125]
Bitwise NOT output:  [  -3   -9 -126]


#### numpy.binary_repr: Finding Binary Represenatation of a number

(number, width=None)

This function is used to represent binary form of the input number as a string.For negative numbers, if width is not given, a minus sign is added to the front. If width is given, the two’s complement of the number is returned, with respect to that width.

In [182]:
in_num = -10
print ("Input  number : ", in_num)

out_num1 = np.binary_repr(in_num) 
print ("binary representation of -10 without width : ", out_num1) 

out_num2 = np.binary_repr(in_num,width=6) 
print ("binary representation of -10 with width : ", out_num2) 

Input  number :  -10
binary representation of -10 without width :  -1010
binary representation of -10 with width :  110110


In [184]:
in_num = -5
print ("Input  number : ", in_num)

out_num1 = np.binary_repr(in_num) 
print ("binary representation of -5 without width : ", out_num1) 

out_num2 = np.binary_repr(in_num,width=5) 
print ("binary representation of -5 with width : ", out_num2)

Input  number :  -5
binary representation of -5 without width :  -101
binary representation of -5 with width :  11011


#### Numpy | Linear Algebra : np.linalg.

The Linear Algebra module of NumPy offers various methods to apply linear algebra on any numpy array.
One can find:

- rank, determinant, trace, etc. of an array.
- eigen values of matrices
- matrix and vector products (dot, inner, outer,etc. product), matrix exponentiation
- solve linear or tensor equations and much more!

In [186]:
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])

print("matrix A: ",A)
 
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))           #corresponds to the maximal number of linearly independent columns of A. 
 
# Trace of matrix A
print("\nTrace of A:", np.trace(A))  

# the trace of a square matrix A, denoted tr(A), 
#is defined to be the sum of elements on the main diagonal (from the upper left to the lower right) of A. 
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))


matrix A:  [[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


##### numpy.linalg.eigh(a) :  h in eigh for  hermitian/ Conjugate matrix

This function is used to return the eigenvalues and eigenvectors of a complex conjugate symmetric or a real symmetric matrix.

Returns two objects:
- a 1-D array containing the eigenvalues of a, 
- and a 2-D square array of the corresponding eigenvectors (in columns).

In [190]:
a = np.array([[1, -2j], [2j, 5]])
 
print("Array is :",a)
 
from numpy import linalg

# calculating an eigen value
# using eigh() function
c, d = np.linalg.eigh(a)
 
print("\nEigen value is :", c)
print("\nEigen value is :", d)

Array is : [[ 1.+0.j -0.-2.j]
 [ 0.+2.j  5.+0.j]]

Eigen value is : [0.17157288 5.82842712]

Eigen value is : [[-0.92387953+0.j         -0.38268343+0.j        ]
 [ 0.        +0.38268343j  0.        -0.92387953j]]


#### numpy.linalg.eig(a) : This function is used to compute the eigenvalues and right eigenvectors of a square array.

In [195]:
# Python program explaining eig() function
 
from numpy import linalg
 
# Creating an array using diag function
a = np.diag((1, 2, 3))
 
print("Array is :",a)
 
# calculating an eigen value using eig() function
c,d = np.linalg.eig(a)
 
print("\nEigen value is :",c)
print("\nEigen value is :",d)

Array is : [[1 0 0]
 [0 2 0]
 [0 0 3]]

Eigen value is : [1. 2. 3.]

Eigen value is : [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### OTHERS:

In [207]:
a = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
print(a)

a = a.tolist()
print(a)

a = np.sort(a,axis=0)        #axos = 1 : across
                            #axis = 0 : down
print(a)

a = np.sort(a,axis=1)
print(a)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[6, 1, 1], [4, -2, 5], [2, 8, 7]]
[[ 2 -2  1]
 [ 4  1  5]
 [ 6  8  7]]
[[-2  1  2]
 [ 1  4  5]
 [ 6  7  8]]


#### Random Numbers in NumPy

In [219]:
from numpy import random
a = np.random
np.info(a)

Random Number Generation

Use ``default_rng()`` to create a `Generator` and call its methods.

=============== =========================================================
Generator
--------------- ---------------------------------------------------------
Generator       Class implementing all of the random number distributions
default_rng     Default constructor for ``Generator``
=============== =========================================================

============================================= ===
BitGenerator Streams that work with Generator
--------------------------------------------- ---
MT19937
PCG64
Philox
SFC64
============================================= ===

============================================= ===
Getting entropy to initialize a BitGenerator
--------------------------------------------- ---
SeedSequence
============================================= ===


Legacy
------

For backwards compatibility with previous versions of numpy before 1.17, the
various aliases to

#### random integer from 0 to 100

In [220]:
x = np.random.randint(100)
x

67

In [221]:
x = np.random.randint(90,100)
x

93

#### Random Float

In [223]:
x = np.random.rand()
x

0.21195631323947028

#### Random Array

In [228]:
x = np.random.randint(100,size=5)    #1-d Array
print(x)

x = np.random.randint(100,size=(3,5))    #2-d Array
print("\n",x)

[ 0 34 53 70 80]

 [[57  4 33 74 95]
 [13 91 98 44 34]
 [16 37 88 81 72]]


#### Random Array using float

In [233]:
#Doesnt provide size parameter

x = np.random.rand(3,5)    #2-d Array
print("\n",x)

x = np.random.rand(5)    #1-d Array
print("\n",x)


 [[0.80374286 0.22639859 0.55214935 0.14681899 0.41942073]
 [0.09263491 0.42682415 0.44640579 0.38738242 0.65775025]
 [0.55305974 0.6093657  0.78962814 0.16991235 0.28015652]]

 [0.05411611 0.38389297 0.08763905 0.13241936 0.54147698]


#### Generate Random Number From Array: Using Choice

The choice() method takes an array as a parameter and randomly returns one of the values.

In [237]:
x = random.choice([3, 5, 7, 9])
print(x)

#Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):
x = random.choice([3,5,12,67,89,9,80,43],size=(5,3))


5

 [[89  5 89]
 [67  5 12]
 [ 5 89  9]
 [ 5 12  3]
 [67  5  5]]


#### Copying

In [238]:
a = np.copy(x)
print("copy of x",a)

copy of x [[89  5 89]
 [67  5 12]
 [ 5 89  9]
 [ 5 12  3]
 [67  5  5]]


In [243]:
a.dtype

dtype('int32')

#### Adding/removing Elements

In [286]:
x = random.choice([3,5,12,67,89,9,80,43],size=(5,3))

y =random.choice([3,5,12,67,89,9,80,43],size=(5,3))

np.append(x,y,axis=0)
print(x)

x = np.array([[1,2,3],[4,5,6]])
x = np.insert(x,1,[12,4,3],axis= 0)   #insert after position 1
print(x)

x = np.array([[1,2.3,3],[12,4,3],[4,5,6]])
x = np.delete(x,1,axis= 0)   #insert after position 1
print(x)

print((x>3) & (x<10))

print(np.floor(x))

[[ 3  3  9]
 [67  5 12]
 [12  3 43]
 [ 5  3 89]
 [ 9 43 12]]
[[ 1  2  3]
 [12  4  3]
 [ 4  5  6]]
[[1.  2.3 3. ]
 [4.  5.  6. ]]
[[False False False]
 [ True  True  True]]
[[1. 2. 3.]
 [4. 5. 6.]]


#### Combining/splitting

In [247]:
a = np.random.randint(0,100,size=(5,3))
b = np.random.randint(20,100,size=(5,3))

c = np.concatenate((a,b),axis=0)
print(c)

c = np.concatenate((a,b),axis=1)
print(c)

[[17 34 22]
 [98 81  3]
 [51 87 28]
 [38 95 40]
 [90  3 16]
 [40 42 66]
 [24 21 83]
 [68 88 93]
 [70 91 47]
 [66 83 92]]
[[17 34 22 40 42 66]
 [98 81  3 24 21 83]
 [51 87 28 68 88 93]
 [38 95 40 70 91 47]
 [90  3 16 66 83 92]]


##### Splitting array

In [257]:
a = np.random.randint(0,100,size=(8,4))

c = np.split(a,2)       #split in 2 array
print(c)

c = np.split(a,4)       #split in 4 array: all array size must be equal while split
print("\n",c)

c = np.split(a,2,axis=1)       #split in 4 array: all array size must be equal while split
print(c)

[array([[68, 20, 56, 96],
       [35, 66,  8, 72],
       [89, 49, 89, 85],
       [42, 90,  9, 52]]), array([[22, 33, 69, 51],
       [95, 16, 29, 39],
       [48, 38, 74, 10],
       [94, 20, 77, 15]])]

 [array([[68, 20, 56, 96],
       [35, 66,  8, 72]]), array([[89, 49, 89, 85],
       [42, 90,  9, 52]]), array([[22, 33, 69, 51],
       [95, 16, 29, 39]]), array([[48, 38, 74, 10],
       [94, 20, 77, 15]])]
[array([[68, 20],
       [35, 66],
       [89, 49],
       [42, 90],
       [22, 33],
       [95, 16],
       [48, 38],
       [94, 20]]), array([[56, 96],
       [ 8, 72],
       [89, 85],
       [ 9, 52],
       [69, 51],
       [29, 39],
       [74, 10],
       [77, 15]])]


#### Statistics:

In [292]:
x = np.array([[1,2.3,3],[12,4,3],[4,5,6]])

print(np.mean(x,axis=0))

print(np.var(x,axis=0))

print(np.std(x,axis=0))

print(np.corrcoef(x))

print(np.min(x))

print(np.max(x))

[5.66666667 3.76666667 4.        ]
[21.55555556  1.24222222  2.        ]
[4.64279609 1.11455023 1.41421356]
[[ 1.         -0.96877366  0.98532928]
 [-0.96877366  1.         -0.91224546]
 [ 0.98532928 -0.91224546  1.        ]]
1.0
12.0
